<?php
   $products = $this->getProducts()->getData();
?>

<head>
    <style>
   .container {
        height: 100vh;
        width: 100vw;
    }

    </style>
</head>


    <div class="container mt-5">
        <h3 class="title mt-2">Product Details :</h3>
        <a href="<?php echo $this->getUrl("add");?>"><button type="submit" name="submit" class="btn btn-primary mt-1">Add</button></a>
        <div class="mt-3 table-responsive">

            <table class="table table-hover-table-striped table-bordered mt-2 ">

                <thead>

                    <tr>
                        <th>Product Id</th>
                        <th>Product Name</th>
                        <th>Manufacturer</th>
                        <th>Quantity</th>
                        <th>PKD</th>
                        <th>Status</th>
                        <th>Expiry Date</th>
                        <th>Description</th>
                        <th>Entry date</th>
                        <th>Modify date</th>
                        <th>Base</th>
                        <th>Thumbnail</th>
                        <th>Small</th>
                        <th>Action</th>
                        <th>Gallery</th>
                    </tr>

                </thead>
                <tbody>

                    <?php  foreach($products as $product){ ?>
                    <tr>
                        
                        <td><?php echo $product->productId; ?></td>
                        <td><?php echo $product->name; ?></td>
                        <td><?php echo $product->manufacturer; ?></td>
                        <td><?php echo $product->quantity; ?></td>
                        <td><?php echo $product->pkd; ?></td>
                        <td><?php echo $product->status; ?></td>
                        <td><?php echo $product->expiryDate; ?></td>
                        <td><?php echo $product->description; ?></td>
                        <td><?php echo $product->createdDate; ?></td>
                        <td><?php echo $product->updatedDate; ?></td>
                        <td><?php echo $product->base; ?></td>
                        <td><?php echo $product->thumb; ?></td>
                        <td><?php echo $product->small; ?></td>
                        <td><a href="<?php echo $this->getUrl("edit","Product",['id'=>$product->productId]);?>" class="btn btn-primary">Edit</a> 
                        <a href="<?php echo $this->getUrl("delete","Product",['id'=>$product->productId]);?>" class="btn btn-danger mt-1">Delete</a></td>
                        <td><a href="<?php echo $this->getUrl("grid","product_media",['id'=>$product->productId]);?>" class="btn btn-primary">Media Gallery</a></td>
                    </tr>
                    <?php  }?>
                </tbody>
            </table>
        </div>
       </div>
    </div>
    
