<head>
    <style>
   .container {
        height: 100vh;
        width: 100vw;
    }

    </style>
</head>
<?php       
        $mediaArray = $this->getMedia()->getData();
        $id = $this->getRequest()->getParams('id');
        $product = $this->getProduct();  
?>
<div class="container">

<h3>Product Media</h3>
<form action="<?php echo $this->getUrl("updateImage","product_media",['id'=>$product->productId]);?>" enctype="multipart/form-data" method="POST">
    <div class=" col-sm-6" style="margin-left:91%"; >
        <a href=""><button type="submit" class="btn btn-primary">Update</button></a>
    </div>
    <div class="table-responsive">
        <table class="table table-hover-table-striped table-bordered mt-2  ">

            <thead>

                <tr>
                    <th>Image</th>
                    <th>Label</th>
                    <th>Small</th>
                    <th>Thumb</th>
                    <th>Base</th>
                    <th>Gallery</th>
                    <th>Remove</th>
                </tr>

            </thead>
            <tbody>
                <?php if(!$mediaArray): ?>
                <tr>
                    <td colspan="7">
                        <center>No Image Found.</center>
                    </td>
                </tr>
                <?php else: ?>
                <?php foreach($mediaArray as $media):?>
                <tr>
                    <td style="text-align:center" value="<?php echo $media->image ?>">
                        <img src="<?php echo $media->image ?>" height="100" width="100">
                    </td>
                    <td style="text-align:center"><input type="text" name="label[<?php echo $media->mediaId ?>]" value="<?php echo $media->label; ?>"></td>
                    <td style="text-align:center"><input type="radio" name="small" value="<?php echo $media->mediaId ?>" <?php if($product->small == $media->mediaId){echo "checked";}?>></td>
                    <td style="text-align:center"><input type="radio" name="thumb" value="<?php echo $media->mediaId ?>" <?php if($product->thumb == $media->mediaId){echo "checked";}?>></td>
                    <td style="text-align:center"><input type="radio" name="base"value="<?php echo $media->mediaId ?>" <?php if($product->base == $media->mediaId){echo "checked";}?>></td>
                    <td style="text-align:center"><input type="checkbox" name="gallery[<?php echo $media->mediaId ?>]" <?php if($media->isGallery){echo "checked";}?>></td>
                    <td style="text-align:center"><input type="checkbox" name="remove[<?php echo $media->mediaId ?>]" value="<?php echo $media->mediaId ?>"></td>
                </tr>
                <?php endforeach;?>
                <?php endif;?>
                
            </tbody>
        </table>
    </div>

</form>

<form action="<?php echo $this->getUrl('addImage','product_media',['id'=>$id]);?>" method="post" enctype="multipart/form-data">
    <div class="row mt-3" style="margin-left:66%";>
            <input type="file" name="image" id="image" value="Browse">

        <button type="submit" name="submit" class="btn btn-primary">Upload</button>

    </div>
</form>

</div>
