<?php 
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Shipping</title>
    <style>
    .container {
       width: 40vw;
        padding: 10px;

    }

    h2 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }

  

    </style>
</head>

<body>
<?php 
 $shipping = $this->getShipping(); 
 $statusOptions = $shipping->getStatusOptions();

?>
    <div class="container mt-5">
        <h2 class="mt-2">Shipping Details Form</h2>
            <form action="<?php echo $this->getUrl('save','shipping',['id'=>$shipping->methodId]); ?>" method="post">
                <div class="form-group col-sm-6">
                    <label for="product">Method name</label>
                    <input type="text" class="form-control" name="shipping[name]"  value="<?php echo $shipping->name ?>" required>
                    
                </div>
                <div class="form-group col-sm-6">
                        <label for="product">Price</label>
                        <input type="number" class="form-control" value="<?php echo $shipping->price; ?>" name="shipping[price]" required>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="product">Discount</label>
                        <input type="number" class="form-control" value="<?php echo $shipping->discount; ?>" name="shipping[discount]" required>
                    </div>
                <div class="form-group col-sm-6">
                    <label for="shipping[status]">Status</label>
                    <select name="shipping[status]" id="" class="form-control" >
                           <?php foreach($statusOptions as $key => $option){?>
                           <option value="<?php echo $option ?>" <?php  if ($shipping->status == $option){ echo "selected"; } ?> > <?php echo $option; ?></option>
                           <?php } ?>
                    </select>
                </div>
                    <button type="submit" name="submit" class="btn btn-primary mt-1">Save</button>
                <a href="<?php echo $this->getUrl('grid','shipping',['id'=>$shipping->methodId],true); ?>" name="submit" class="btn btn-success mt-1">Return</a>
            </form>
    </div>


</body>

</html>