<?php
   $shippings = $this->getShippings()->getData();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Shipping</title>
    <style>
    h3 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }
    .container{ 
        height: 50vh;
        width: 50vw;
    }
    </style>
</head>

<body>
    <div class="container mt-5">
        <h3 class="title mt-2">Shipping Details</h3>
        <a href="?c=shipping&a=add"><button type="submit" name="submit" class="btn btn-primary mt-1">Add</button></a>
        <div class="mt-3">

            <table class="table table-hover-table-striped table-bordered mt-2 ">

                <thead>

                    <tr>
                        <th>Method Id</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Discount</th>
                        <th>Status</th>
                        <th>Create Date</th>
                        <th>Action</th>
                    </tr>

                </thead>
                <tbody>

                    <?php  foreach($shippings as $shipping){ ?>
                    <tr>
                        
                        <td><?php echo $shipping->methodId; ?></td>
                        <td><?php echo $shipping->name; ?></td>
                        <td><?php echo $shipping->price; ?></td>
                        <td><?php echo $shipping->discount; ?></td>
                        <td><?php echo $shipping->status; ?></td>
                        <td><?php echo $shipping->createdDate; ?></td>
                      
                        <td><a href="?c=shipping&a=edit&id=<?php echo $shipping->methodId; ?>" class="btn btn-primary">Edit</a> 
                        <a href="?c=shipping&a=delete&id=<?php echo $shipping->methodId; ?>" class="btn btn-danger mt-1">Delete</a></td>
                    </tr>
                    <?php  }?>
                </tbody>
            </table>
        </div>
       </div>
    </div>
    
</body>
</html>