
    <div class="main mt-5">
        <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link active btn btn-success" aria-current="page" href="index.php">Manu</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="?c=category&a=grid">Category</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="?c=customer&a=grid">Customer</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="?c=Product&a=grid">Product</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="?c=payment&a=grid">Payment</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="?c=shipping&a=grid">Shipping</a></li>
               
        </ul>
    </div>