
    <div class="main mt-5">
        <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link active btn btn-success" aria-current="page" href="index.php">Manu</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="<?php echo $this->getUrl('grid','category'); ?>">Category</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="<?php echo $this->getUrl('grid','customer'); ?>">Customer</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="<?php echo $this->getUrl('grid','product'); ?>">Product</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="<?php echo $this->getUrl('grid','payment'); ?>">Payment</a></li>
            <li class="nav-item"><a class="nav-link active btn btn-success" href="<?php echo $this->getUrl('grid','shipping'); ?>">Shipping</a></li>
               
        </ul>
    </div>