<?php
$customers = $this->getCustomers()->getData();

// echo "<pre>";
// print_r($customers);
// die();

?>

<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
         integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <title>Customer</title>
     <style>
     body {
         height: 100%;
         width: 100%;
     }

     .title {
         background-color: black;
         color: wheat;
         font-size: 30px;
         text-align: center;
         border-radius: 5px;
     }
     </style>
</head>

 <body>
    <div class="container mt-5">
        <h3 class="title mt-2">Customer Details</h3>

            <div class="mt-3">
            <a href="?c=customer&a=add"><button type="submit" name="submit" class="btn btn-primary mt-1">Add</button></a>

                <table class="table table-hover-table-striped table-bordered table-responsive mt-2 ">

                    <thead>

                        <tr>
                            <th>Customer Id</th>
                            <th>Customer Name</th>
                            <th>Last Name</th>
                            <th>DOB</th>
                            <th>Customer Email: </th>
                            <th>Contact</th>
                            <th>Gender</th>
                            <th>Entry date</th>
                            <th>Modify date</th>
                            <th>Home name </th>
                            <th>Sreet adsess</th>
                            <th>Landmark</th>
                            <th>City</th>
                            <th>Pin code</th>
                            <th>State</th>
                            <th>action</th>
                        </tr>

                    </thead>
                    <tbody>
                    <?php foreach ($customers as $customer) {?>
                        <tr>
                            <td><?php echo $customer->customerId; ?></td>
                            <td><?php echo $customer->firstName; ?></td>
                            <td><?php echo $customer->lastName; ?></td>
                            <td><?php echo $customer->dateOfBirth; ?></td>
                            <td><?php echo $customer->email; ?> </td>
                            <td><?php echo $customer->contact; ?></td>
                            <td><?php echo $customer->gender; ?></td>
                            <td><?php echo $customer->createdDate; ?></td>
                            <td><?php echo $customer->updatedDate; ?></td>
                            <td><?php echo $customer->homeName; ?> </td>
                            <td><?php echo $customer->street; ?></td>
                            <td><?php echo $customer->landmark; ?></td>
                            <td><?php echo $customer->city; ?></td>
                            <td><?php echo $customer->code; ?></td>
                            <td><?php echo $customer->state; ?></td>
                            <td><a href="?c=customer&a=edit&id=<?php echo $customer->customerId; ?>" class="btn btn-primary">Edit</a>
                            <a href="?c=customer&a=delete&id=<?php echo $customer->customerId; ?>" class="btn btn-danger mt-1">Delete</a></td>

                        </tr>

                        <?php }?>

                    </tbody>
                </table>
            </div>

        </div>
    </div>




 </body>

 </html>