<?php 
$payment = $this->getPayment(); 
$statusOptions = $payment->getStatusOptions();

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Payment</title>
    <style>
    .container {
        width: 40vw;
        padding: 10px;

    }

    h2 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }
    </style>
</head>

<body>
    <div class="container mt-5">
        <h2 class="mt-2"> Payment Details Form</h2>

        <form action="?c=payment&a=save&id=<?php echo $payment->methodId; ?>" method="post">

            <div class="row">
                <div class="form-group col-sm-6">
                    <label for="product">Method name</label>
                    <input type="text" class="form-control" name="payment[name]" value="<?php echo $payment->name ?>"
                        required>

                </div>
                <div class="form-group col-sm-6">
                    <label for="product">Transaction Id</label>
                    <input type="number" class="form-control" name="payment[transactionId]"
                        value="<?php echo $payment->transactionId ?>" required>
                </div>
            </div>
            <div class="form-group col-sm-6">
                <label for="payment[status]">Status</label>
                <select name="payment[status]" id="" class="form-control">
                    <?php foreach($statusOptions as $key => $option){?>
                    <option value="<?php echo $option ?>"
                        <?php  if ($payment->status == $option){ echo "selected"; } ?>> <?php echo $option; ?></option>
                    <?php } ?>
                </select>
            </div>

            <label for="payment[description]">Discription</label>
            <div>
                <textarea name="payment[description]" id="" cols="30"
                    rows="5"><?php echo $payment->description; ?></textarea>
            </div>
            <button type="submit" name="submit" class="btn btn-primary mt-1">Save</button>
            <a href="?c=payment&a=grid" name="submit" class="btn btn-success mt-1">Return</a>
        </form>
    </div>


</body>

</html>