<?php
   $payments = $this->getPayments()->getData();
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Payment</title>
    <style>
    .container{
        height: 50vh;
        width: 50vw;
       
    }

    h3 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }
    </style>
</head>

<body>
    <div class="container mt-5">
        <h3 class="title mt-2">Payment Details</h3>
        <a href="<?php echo $this->getUrl('add','payment'); ?>"><button type="submit" name="submit" class="btn btn-primary mt-1">Add</button></a>
        <div class="mt-3">

            <table class="table table-hover-table-striped table-bordered mt-2 ">

                <thead>

                    <tr>
                        <th>Method Id</th>
                        <th>Name</th>
                        <th>Transaction Id</th>
                        <th>Status</th>
                        <th>Description</th>
                        <th>Create Date</th>
                        <th>Action</th>
                    </tr>

                </thead>
                <tbody>

                    <?php  foreach($payments as $payment){ ?>
                    <tr>
                        
                        <td><?php echo $payment->methodId; ?></td>
                        <td><?php echo $payment->name; ?></td>
                        <td><?php echo $payment->transactionId; ?></td>
                        <td><?php echo $payment->status; ?></td>
                        <td><?php echo $payment->description; ?></td>
                        <td><?php echo $payment->createdDate; ?></td>
                      
                        <td><a href="<?php echo $this->getUrl('edit','payment',['id'=>$payment->methodId]); ?>" class="btn btn-primary">Edit</a> 
                        <a href="<?php echo $this->getUrl('delete','payment',['id'=>$payment->methodId]); ?>" class="btn btn-danger mt-1">Delete</a></td>
                    </tr>
                    <?php  }?>
                </tbody>
            </table>
        </div>
       </div>
    </div>
    
</body>
</html>