<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Category</title>
    <style>
    body {
        height: 40vh;
        width: 40vw;
        display: flex;
        align-items: center;   
    }

    h3 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }
    </style>
</head>

<body>
    <div class="container mt-5 ">
        <h3 class="title mt-2">Delete Category </h3>
        <div>
            <form action="" method="post">
                <button type="submit" name="all" class="btn btn-primary">Delete All</button>
                <button type="submit" name="one" class="btn btn-primary">Delete One</button>
                <a href="?c=category&a=grid" name="submit" class="btn btn-success mt-1">Return</a>

            </form>
        </div>
    </div>
</body>

</html>