<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Add Customer</title>
    <style>
    .container {
        padding: 10px;
    }

    h1 {
        background-color: black;
        color: wheat;
        text-align: center;
        border-radius: 5px;
    }

    hr {
        background-color: black;
    }

    .radio {
        margin: 5px;
    }
    </style>
</head>

<body>
    <?php
    $category = $this->getCategory();
    $categorys = $this->getCategories()->getData(); 
    $statusOptions = $category->getStatusOptions(); ?>
    <div class="container mt-5">
        <h1 class="mt-2">Category Details Form</h1>
        <div class="personal data mt-3 ">
            <h3>Category information </h3>
            <form action="?c=category&a=save&id=<?php echo $category->categoryId; ?>" method="post">
                <div class="row">
                    <div class="form-group col-sm-6">
                        <label for="categotyId">Category </label>
                        <select name="Category[parentId]" id="" class="form-control">
                            <option>Select Category</option>
                            <option value="0">Root Category</option>
                            <?php foreach($categorys as $value){?>
                            <option value="<?php echo $value->categoryId;?>"
                                <?php if($value->categoryId == $category->categoryId ){echo "selected";} ?>>
                                <?php echo $value->pathIds;?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="Category[categoryName]">Category name</label>

                        <input type="text" class="form-control" name="Category[categoryName]"
                            value="<?php echo $category->categoryName; ?>" required>
                    </div>
                </div>
                <div class="form-group col-sm-6">
                    <label for="Category[status]">Status</label>
                    <select name="Category[status]" id="" class="form-control" >
                           <?php foreach($statusOptions as $key => $option){?>
                           <option value="<?php echo $option ?>" <?php  if ($category->status == $option){ echo "selected"; } ?> > <?php echo $option; ?></option>
                           <?php } ?>
                    </select>
                </div>
                        
                <button type="submit" name="submit" class="btn btn-primary mt-1">Save</button>
                <a href="?c=category&a=grid" name="submit" class="btn btn-success mt-1">Return</a>

            </form>
        </div>
</body>

</html>